import { Footer } from "@/features/footer";
import Header from "@/features/header";

import { DefaultButton } from "@/shared/ui/buttons";
import { DarkLayout } from "@/shared/ui/layouts";
import { SectionTitle, TextP } from "@/shared/ui/text-components";

import dgesLogo from "/images/ar-nft/dges-icon.svg";
import appStoreButton from "/images/landing/get-started-section/app-store-button.svg";
import playMarketButton from "/images/landing/get-started-section/play-market-button.svg";

import phone1 from "/images/ar-nft/phone_33.webp";
import phone2 from "/images/ar-nft/phone_34.webp";
import nftStPhone from "/images/blockchain/phone_20.webp";

const ArNftPage = () => {
    return (
        <DarkLayout
            className="flex flex-col justify-between 
               bg-[url(/images/product/bg.svg)] bg-cover bg-no-repeat bg-center
               pt-20 lg:pt-40"
        >
            <Header white />
            <div
                className="container mx-auto
                            grid grid-cols-12 gap-1
            "
            >
                <div className="col-span-12 bg-smoky-black-bg px-4 py-6 md:p-10">
                    <div className="flex flex-col lg:flex-row gap-10">
                        <div className="flex gap-4 mx-auto lg:hidden">
                            <img
                                src={phone1}
                                className="object-contain h-full max-h-[50vh] lg:max-h-[40vh] max-w-[40vw]"
                            />
                            <img
                                src={phone2}
                                className="object-contain h-full max-h-[50vh] lg:max-h-[40vh] max-w-[40vw]"
                            />
                        </div>

                        <img src={phone1} className="object-contain max-h-[50vh] lg:max-h-[40vh] hidden lg:block" />
                        <img src={phone2} className="object-contain max-h-[50vh] lg:max-h-[40vh] hidden lg:block" />

                        <div className="flex flex-col">
                            <SectionTitle title="AR NFT" className="text-white" />
                            <h2 className="manrope-medium-22 text-white mt-6">We are more than just AR technologies</h2>
                            <TextP className="text-spanish-gray mt-4">
                                AR NFTs are generated by the decentralised geolocation ecosystem DGES, enhancing the
                                reliability of interactions in augmented reality and simplifying NFT integration. This
                                makes advanced technologies more accessible and efficient.
                            </TextP>
                            <div className="flex gap-10 mt-10 justify-center md:justify-start flex-wrap">
                                <a href={import.meta.env.VITE_APP_NFTST_APPSTORE_URL}>
                                    <DefaultButton className="">
                                        <img src={appStoreButton} />
                                    </DefaultButton>
                                </a>
                                <a href={import.meta.env.VITE_APP_NFTST_PLAYMARKET_URL}>
                                    <DefaultButton className="">
                                        <img src={playMarketButton} />
                                    </DefaultButton>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div
                    className="col-span-12 lg:col-span-7 xl:col-span-4
                             bg-smoky-black-bg flex flex-col px-4 py-6 md:p-10"
                >
                    <SectionTitle title="AR Demo" className="text-white" />
                    <h2 className="manrope-medium-22 text-white mt-6">Test your first AR object now </h2>
                    <TextP className="text-spanish-gray mt-4">
                        This is our Web AR demo experience. You can try it now and explore our solution in practice.
                    </TextP>
                    <a className="mt-auto mx-auto mb-6" href={""}>
                        <DefaultButton className="mt-6">
                            <span className="text-white">Try AR Now</span>
                        </DefaultButton>
                    </a>

                    <NftstText className="hidden lg:flex xl:hidden mt-6" />
                </div>

                <div
                    className="col-span-12 lg:col-span-5 xl:col-span-8 
                              bg-smoky-black-bg flex flex-col md:flex-row gap-6 px-4 py-6 md:p-10"
                >
                    <img src={nftStPhone} className="object-contain h-full max-h-[50vh] lg:max-h-[40vh] m-auto" />

                    <NftstText className="flex lg:hidden xl:flex" />
                </div>
            </div>

            <Footer />
        </DarkLayout>
    );
};

const NftstText = ({ className }: { className?: string }) => {
    return (
        <div className={`flex flex-col ${className ?? ""}`}>
            <img src={dgesLogo} className="h-10 mr-auto" />
            <h2 className="manrope-medium-22 text-white mt-6">Decentralized Geo Ecosystem </h2>
            <TextP className="text-spanish-gray mt-4">
                DGES (Decentralized Geolocation Ecosystem) is an independent system of open-source smart contracts
                across multiple blockchain networks. Bypassing intermediaries, it provides a secure environment for the
                efficient, unrestricted recording, tracking, and management of data. DGES offers a scalable
                infrastructure for application developers, organizations operating in the physical sector, and consumers
                of goods and services.
            </TextP>
            <a className="mt-auto mx-auto mb-6" href={import.meta.env.VITE_APP_DGES_URL}>
                <DefaultButton className="mt-6">
                    <span className="text-white">DGES</span>
                </DefaultButton>
            </a>
        </div>
    );
};

export { ArNftPage };
